# Generated by Django 4.2.7 on 2025-06-01 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание деятельности')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Краткое описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип компании')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='company_banners/', verbose_name='Баннер компании')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('country', models.CharField(default='Россия', max_length=100, verbose_name='Страна')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год основания')),
                ('company_size', models.CharField(blank=True, choices=[('startup', 'Стартап'), ('small', 'Малая (до 50 сотрудников)'), ('medium', 'Средняя (50-250 сотрудников)'), ('large', 'Крупная (250+ сотрудников)'), ('enterprise', 'Корпорация')], max_length=20, verbose_name='Размер компании')),
                ('employees_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество сотрудников')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('favorites_count', models.PositiveIntegerField(default=0, verbose_name='Количество добавлений в избранное')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирована')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта/услуги')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company_products/', verbose_name='Изображение')),
                ('price_info', models.CharField(blank=True, max_length=100, verbose_name='Информация о цене')),
                ('product_url', models.URLField(blank=True, verbose_name='Ссылка на продукт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Продукт компании',
                'verbose_name_plural': 'Продукты компании',
                'db_table': 'company_products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 звезда'), (2, '2 звезды'), (3, '3 звезды'), (4, '4 звезды'), (5, '5 звезд')], verbose_name='Рейтинг')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок отзыва')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Одобрен')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('moderator_notes', models.TextField(blank=True, verbose_name='Заметки модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Отзыв о компании',
                'verbose_name_plural': 'Отзывы о компаниях',
                'db_table': 'company_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participation_type', models.CharField(choices=[('exhibitor', 'Экспонент'), ('sponsor', 'Спонсор'), ('partner', 'Партнер'), ('speaker', 'Спикер')], default='exhibitor', max_length=20, verbose_name='Тип участия')),
                ('booth_number', models.CharField(blank=True, max_length=20, verbose_name='Номер стенда')),
                ('booth_size', models.CharField(blank=True, max_length=50, verbose_name='Размер стенда')),
                ('special_offers', models.TextField(blank=True, verbose_name='Специальные предложения')),
                ('presentation_title', models.CharField(blank=True, max_length=200, verbose_name='Название презентации')),
                ('presentation_time', models.DateTimeField(blank=True, null=True, verbose_name='Время презентации')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('contact_position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('favorites_count', models.PositiveIntegerField(default=0, verbose_name='Количество добавлений в избранное')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемый участник')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Участник выставки',
                'verbose_name_plural': 'Участники выставки',
                'db_table': 'exhibition_participants',
                'ordering': ['company__name'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Избранная компания',
                'verbose_name_plural': 'Избранные компании',
                'db_table': 'favorite_companies',
            },
        ),
    ]
