# Generated by Django 4.2.7 on 2025-06-01 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoritecompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_companies', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='exhibitionparticipant',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='exhibitionparticipant',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='exhibitions.exhibition', verbose_name='Выставка'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='companyreview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='companyproduct',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='exhibitions.category', verbose_name='Категория деятельности'),
        ),
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_companies', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritecompany',
            unique_together={('user', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='exhibitionparticipant',
            unique_together={('exhibition', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='companyreview',
            unique_together={('company', 'user')},
        ),
    ]
