# Generated by Django 4.2.7 on 2025-06-01 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='Иконка категории')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название выставки')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.CharField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок регистрации')),
                ('venue_name', models.CharField(max_length=200, verbose_name='Название площадки')),
                ('address', models.TextField(verbose_name='Адрес проведения')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('country', models.CharField(default='Россия', max_length=100, verbose_name='Страна')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Долгота')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='exhibition_logos/', verbose_name='Логотип выставки')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='exhibition_banners/', verbose_name='Баннер')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Контактное лицо')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Контактный email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Контактный телефон')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('requires_changes', 'Требуются изменения'), ('published', 'Опубликовано'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Причина отклонения')),
                ('moderator_notes', models.TextField(blank=True, verbose_name='Заметки модератора')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')),
                ('favorites_count', models.PositiveIntegerField(default=0, verbose_name='Количество добавлений в избранное')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('is_free', models.BooleanField(default=False, verbose_name='Бесплатное участие')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальное количество участников')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
                'db_table': 'exhibitions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='exhibition_documents/', verbose_name='Файл')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Документ выставки',
                'verbose_name_plural': 'Документы выставки',
                'db_table': 'exhibition_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExhibitionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exhibition_images/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Изображение выставки',
                'verbose_name_plural': 'Изображения выставки',
                'db_table': 'exhibition_images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='exhibitions.exhibition', verbose_name='Выставка')),
            ],
            options={
                'verbose_name': 'Избранная выставка',
                'verbose_name_plural': 'Избранные выставки',
                'db_table': 'favorite_exhibitions',
            },
        ),
    ]
