# Generated by Django 4.2.7 on 2025-06-01 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exhibitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteexhibition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_exhibitions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='exhibitionimage',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exhibitions.exhibition', verbose_name='Выставка'),
        ),
        migrations.AddField(
            model_name='exhibitiondocument',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='exhibitions.exhibition', verbose_name='Выставка'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exhibitions', to='exhibitions.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_exhibitions', to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteexhibition',
            unique_together={('user', 'exhibition')},
        ),
    ]
