# Generated by Django 4.2.7 on 2025-06-01 02:34

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Номер счета')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('sent', 'Отправлен'), ('paid', 'Оплачен'), ('overdue', 'Просрочен'), ('cancelled', 'Отменен')], default='draft', max_length=20, verbose_name='Статус')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Дата выставления')),
                ('due_date', models.DateField(verbose_name='Срок оплаты')),
                ('company_name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('company_address', models.TextField(verbose_name='Адрес компании')),
                ('company_inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('company_kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('completed', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возвращено'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус')),
                ('payment_method', models.CharField(choices=[('online', 'Онлайн-платеж'), ('invoice', 'По счету'), ('bank_transfer', 'Банковский перевод')], default='online', max_length=20, verbose_name='Способ оплаты')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Внешний ID платежа')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('basic', 'Базовая'), ('standard', 'Стандартная'), ('professional', 'Профессиональная'), ('exclusive', 'Эксклюзивная')], max_length=100, unique=True, verbose_name='Тип плана')),
                ('display_name', models.CharField(max_length=100, verbose_name='Название для отображения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Цена за месяц (руб.)')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Цена за год (руб.)')),
                ('max_exhibitions', models.PositiveIntegerField(default=1, verbose_name='Максимальное количество выставок')),
                ('max_companies_per_exhibition', models.PositiveIntegerField(default=10, verbose_name='Максимальное количество компаний на выставку')),
                ('has_advanced_analytics', models.BooleanField(default=False, verbose_name='Расширенная аналитика')),
                ('has_custom_cards', models.BooleanField(default=False, verbose_name='Кастомизация карточек')),
                ('has_promotion_tools', models.BooleanField(default=False, verbose_name='Инструменты продвижения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'План подписки',
                'verbose_name_plural': 'Планы подписок',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('expired', 'Истекла'), ('cancelled', 'Отменена'), ('pending', 'Ожидает оплаты')], default='pending', max_length=20, verbose_name='Статус')),
                ('billing_period', models.CharField(choices=[('monthly', 'Ежемесячно'), ('yearly', 'Ежегодно')], default='monthly', max_length=20, verbose_name='Период оплаты')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
                ('auto_renewal', models.BooleanField(default=True, verbose_name='Автопродление')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='План подписки')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['-created_at'],
            },
        ),
    ]
